// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (tenant_id, ticket_id, author_id, body, is_internal)
VALUES (?, ?, ?, ?, ?)
RETURNING id, tenant_id, ticket_id, author_id, body, is_internal, created_at
`

type CreateCommentParams struct {
	TenantID   int64  `json:"tenant_id"`
	TicketID   int64  `json:"ticket_id"`
	AuthorID   int64  `json:"author_id"`
	Body       string `json:"body"`
	IsInternal bool   `json:"is_internal"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.TenantID,
		arg.TicketID,
		arg.AuthorID,
		arg.Body,
		arg.IsInternal,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TicketID,
		&i.AuthorID,
		&i.Body,
		&i.IsInternal,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByTicket = `-- name: ListCommentsByTicket :many
SELECT id, tenant_id, ticket_id, author_id, body, is_internal, created_at FROM comments
WHERE tenant_id = ? AND ticket_id = ?
ORDER BY created_at ASC
`

type ListCommentsByTicketParams struct {
	TenantID int64 `json:"tenant_id"`
	TicketID int64 `json:"ticket_id"`
}

func (q *Queries) ListCommentsByTicket(ctx context.Context, arg ListCommentsByTicketParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTicket, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TicketID,
			&i.AuthorID,
			&i.Body,
			&i.IsInternal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCommentsByTicket = `-- name: ListPublicCommentsByTicket :many
SELECT id, tenant_id, ticket_id, author_id, body, is_internal, created_at FROM comments
WHERE tenant_id = ? AND ticket_id = ? AND is_internal = 0
ORDER BY created_at ASC
`

type ListPublicCommentsByTicketParams struct {
	TenantID int64 `json:"tenant_id"`
	TicketID int64 `json:"ticket_id"`
}

func (q *Queries) ListPublicCommentsByTicket(ctx context.Context, arg ListPublicCommentsByTicketParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listPublicCommentsByTicket, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TicketID,
			&i.AuthorID,
			&i.Body,
			&i.IsInternal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
