// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64     `json:"id"`
	TenantID  int64     `json:"tenant_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Comment struct {
	ID         int64     `json:"id"`
	TenantID   int64     `json:"tenant_id"`
	TicketID   int64     `json:"ticket_id"`
	AuthorID   int64     `json:"author_id"`
	Body       string    `json:"body"`
	IsInternal bool      `json:"is_internal"`
	CreatedAt  time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        int64        `json:"id"`
	TenantID  int64        `json:"tenant_id"`
	UserID    int64        `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Team struct {
	ID        int64     `json:"id"`
	TenantID  int64     `json:"tenant_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamMember struct {
	TeamID   int64 `json:"team_id"`
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

type Tenant struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Ticket struct {
	ID             int64         `json:"id"`
	TenantID       int64         `json:"tenant_id"`
	Title          string        `json:"title"`
	Description    string        `json:"description"`
	Status         string        `json:"status"`
	Priority       string        `json:"priority"`
	CategoryID     int64         `json:"category_id"`
	CreatedBy      int64         `json:"created_by"`
	AssignedTo     sql.NullInt64 `json:"assigned_to"`
	AssignedTeamID sql.NullInt64 `json:"assigned_team_id"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	ResolvedAt     sql.NullTime  `json:"resolved_at"`
	ClosedAt       sql.NullTime  `json:"closed_at"`
}

type TicketEvent struct {
	ID        int64          `json:"id"`
	TenantID  int64          `json:"tenant_id"`
	TicketID  int64          `json:"ticket_id"`
	ActorID   int64          `json:"actor_id"`
	Kind      string         `json:"kind"`
	OldValue  sql.NullString `json:"old_value"`
	NewValue  sql.NullString `json:"new_value"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	TenantID     int64     `json:"tenant_id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
