// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE tenant_id = ? AND user_id = ? AND read_at IS NULL
`

type CountUnreadNotificationsParams struct {
	TenantID int64 `json:"tenant_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, arg.TenantID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (tenant_id, user_id, ticket_id, kind, message)
VALUES (?, ?, ?, ?, ?)
RETURNING id, tenant_id, user_id, ticket_id, kind, message, read_at, created_at
`

type CreateNotificationParams struct {
	TenantID int64  `json:"tenant_id"`
	UserID   int64  `json:"user_id"`
	TicketID int64  `json:"ticket_id"`
	Kind     string `json:"kind"`
	Message  string `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.TicketID,
		arg.Kind,
		arg.Message,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TicketID,
		&i.Kind,
		&i.Message,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, tenant_id, user_id, ticket_id, kind, message, read_at, created_at FROM notifications
WHERE tenant_id = ? AND user_id = ? AND id = ?
LIMIT 1
`

type GetNotificationByIDParams struct {
	TenantID int64 `json:"tenant_id"`
	UserID   int64 `json:"user_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, arg.TenantID, arg.UserID, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TicketID,
		&i.Kind,
		&i.Message,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, tenant_id, user_id, ticket_id, kind, message, read_at, created_at FROM notifications
WHERE tenant_id = ?1 AND user_id = ?2
  AND (?3 IS NULL OR read_at IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT ?5 OFFSET ?4
`

type ListNotificationsByUserParams struct {
	TenantID   int64       `json:"tenant_id"`
	UserID     int64       `json:"user_id"`
	UnreadOnly interface{} `json:"unread_only"`
	Offset     int64       `json:"offset"`
	Limit      int64       `json:"limit"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser,
		arg.TenantID,
		arg.UserID,
		arg.UnreadOnly,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TicketID,
			&i.Kind,
			&i.Message,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = ?
WHERE tenant_id = ? AND user_id = ? AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	ReadAt   sql.NullTime `json:"read_at"`
	TenantID int64        `json:"tenant_id"`
	UserID   int64        `json:"user_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, arg.ReadAt, arg.TenantID, arg.UserID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = ?
WHERE tenant_id = ? AND user_id = ? AND id = ? AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ReadAt   sql.NullTime `json:"read_at"`
	TenantID int64        `json:"tenant_id"`
	UserID   int64        `json:"user_id"`
	ID       int64        `json:"id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead,
		arg.ReadAt,
		arg.TenantID,
		arg.UserID,
		arg.ID,
	)
	return err
}
