// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) error
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTenantByID(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error)
	RevokeAllUserTokens(ctx context.Context, arg RevokeAllUserTokensParams) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
}

var _ Querier = (*Queries)(nil)
