// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sla.sql

package db

import (
	"context"
)

const getSLAPolicyByPriority = `-- name: GetSLAPolicyByPriority :one
SELECT id, tenant_id, priority, first_response_mins, resolution_mins, created_at, updated_at FROM sla_policies
WHERE tenant_id = ? AND priority = ?
LIMIT 1
`

type GetSLAPolicyByPriorityParams struct {
	TenantID int64  `json:"tenant_id"`
	Priority string `json:"priority"`
}

func (q *Queries) GetSLAPolicyByPriority(ctx context.Context, arg GetSLAPolicyByPriorityParams) (SlaPolicy, error) {
	row := q.db.QueryRowContext(ctx, getSLAPolicyByPriority, arg.TenantID, arg.Priority)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Priority,
		&i.FirstResponseMins,
		&i.ResolutionMins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSLAPoliciesByTenant = `-- name: ListSLAPoliciesByTenant :many
SELECT id, tenant_id, priority, first_response_mins, resolution_mins, created_at, updated_at FROM sla_policies
WHERE tenant_id = ?
ORDER BY CASE priority
    WHEN 'critical' THEN 0
    WHEN 'high'     THEN 1
    WHEN 'medium'   THEN 2
    WHEN 'low'      THEN 3
END
`

func (q *Queries) ListSLAPoliciesByTenant(ctx context.Context, tenantID int64) ([]SlaPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listSLAPoliciesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlaPolicy{}
	for rows.Next() {
		var i SlaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Priority,
			&i.FirstResponseMins,
			&i.ResolutionMins,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSLAPolicy = `-- name: UpsertSLAPolicy :one
INSERT INTO sla_policies (tenant_id, priority, first_response_mins, resolution_mins)
VALUES (?, ?, ?, ?)
ON CONFLICT (tenant_id, priority)
DO UPDATE SET first_response_mins = excluded.first_response_mins,
              resolution_mins     = excluded.resolution_mins,
              updated_at          = CURRENT_TIMESTAMP
RETURNING id, tenant_id, priority, first_response_mins, resolution_mins, created_at, updated_at
`

type UpsertSLAPolicyParams struct {
	TenantID          int64  `json:"tenant_id"`
	Priority          string `json:"priority"`
	FirstResponseMins int64  `json:"first_response_mins"`
	ResolutionMins    int64  `json:"resolution_mins"`
}

func (q *Queries) UpsertSLAPolicy(ctx context.Context, arg UpsertSLAPolicyParams) (SlaPolicy, error) {
	row := q.db.QueryRowContext(ctx, upsertSLAPolicy,
		arg.TenantID,
		arg.Priority,
		arg.FirstResponseMins,
		arg.ResolutionMins,
	)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Priority,
		&i.FirstResponseMins,
		&i.ResolutionMins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
