// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT OR IGNORE INTO team_members (team_id, user_id, tenant_id)
VALUES (?, ?, ?)
`

type AddTeamMemberParams struct {
	TeamID   int64 `json:"team_id"`
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.TenantID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (tenant_id, name)
VALUES (?, ?)
RETURNING id, tenant_id, name, created_at
`

type CreateTeamParams struct {
	TenantID int64  `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.TenantID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, tenant_id, name, created_at FROM teams
WHERE tenant_id = ? AND id = ?
LIMIT 1
`

type GetTeamByIDParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetTeamByID(ctx context.Context, arg GetTeamByIDParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, arg.TenantID, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamMembersByTenant = `-- name: ListTeamMembersByTenant :many
SELECT tm.team_id, u.id, u.name, u.role
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = ? AND u.is_active = 1
ORDER BY u.name
`

type ListTeamMembersByTenantRow struct {
	TeamID int64  `json:"team_id"`
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Role   string `json:"role"`
}

func (q *Queries) ListTeamMembersByTenant(ctx context.Context, tenantID int64) ([]ListTeamMembersByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersByTenantRow{}
	for rows.Next() {
		var i ListTeamMembersByTenantRow
		if err := rows.Scan(
			&i.TeamID,
			&i.ID,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByTenant = `-- name: ListTeamsByTenant :many
SELECT id, tenant_id, name, created_at FROM teams
WHERE tenant_id = ?
ORDER BY name
`

func (q *Queries) ListTeamsByTenant(ctx context.Context, tenantID int64) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE tenant_id = ? AND team_id = ? AND user_id = ?
`

type RemoveTeamMemberParams struct {
	TenantID int64 `json:"tenant_id"`
	TeamID   int64 `json:"team_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TenantID, arg.TeamID, arg.UserID)
	return err
}
