// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
	"database/sql"
)

const countTicketsByPriority = `-- name: CountTicketsByPriority :many
SELECT priority, COUNT(*) AS total FROM tickets
WHERE tenant_id = ?1
  AND (?2 IS NULL OR created_by = ?2)
GROUP BY priority
`

type CountTicketsByPriorityParams struct {
	TenantID  int64       `json:"tenant_id"`
	CreatedBy interface{} `json:"created_by"`
}

type CountTicketsByPriorityRow struct {
	Priority string `json:"priority"`
	Total    int64  `json:"total"`
}

func (q *Queries) CountTicketsByPriority(ctx context.Context, arg CountTicketsByPriorityParams) ([]CountTicketsByPriorityRow, error) {
	rows, err := q.db.QueryContext(ctx, countTicketsByPriority, arg.TenantID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTicketsByPriorityRow{}
	for rows.Next() {
		var i CountTicketsByPriorityRow
		if err := rows.Scan(&i.Priority, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTicketsByStatus = `-- name: CountTicketsByStatus :many
SELECT status, COUNT(*) AS total FROM tickets
WHERE tenant_id = ?1
  AND (?2 IS NULL OR created_by = ?2)
GROUP BY status
`

type CountTicketsByStatusParams struct {
	TenantID  int64       `json:"tenant_id"`
	CreatedBy interface{} `json:"created_by"`
}

type CountTicketsByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountTicketsByStatus(ctx context.Context, arg CountTicketsByStatusParams) ([]CountTicketsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countTicketsByStatus, arg.TenantID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTicketsByStatusRow{}
	for rows.Next() {
		var i CountTicketsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnassignedActiveTickets = `-- name: CountUnassignedActiveTickets :one
SELECT COUNT(*) FROM tickets
WHERE tenant_id = ?1
  AND (?2 IS NULL OR created_by = ?2)
  AND assigned_to IS NULL
  AND status NOT IN ('resolved', 'closed')
`

type CountUnassignedActiveTicketsParams struct {
	TenantID  int64       `json:"tenant_id"`
	CreatedBy interface{} `json:"created_by"`
}

func (q *Queries) CountUnassignedActiveTickets(ctx context.Context, arg CountUnassignedActiveTicketsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnassignedActiveTickets, arg.TenantID, arg.CreatedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    tenant_id, title, description, status, priority, category_id, created_by,
    first_response_due_at, resolution_due_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, tenant_id, title, description, status, priority, category_id, created_by, assigned_to, assigned_team_id, created_at, updated_at, resolved_at, closed_at, first_response_due_at, resolution_due_at, first_responded_at
`

type CreateTicketParams struct {
	TenantID           int64        `json:"tenant_id"`
	Title              string       `json:"title"`
	Description        string       `json:"description"`
	Status             string       `json:"status"`
	Priority           string       `json:"priority"`
	CategoryID         int64        `json:"category_id"`
	CreatedBy          int64        `json:"created_by"`
	FirstResponseDueAt sql.NullTime `json:"first_response_due_at"`
	ResolutionDueAt    sql.NullTime `json:"resolution_due_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.CategoryID,
		arg.CreatedBy,
		arg.FirstResponseDueAt,
		arg.ResolutionDueAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CategoryID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.AssignedTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.FirstResponseDueAt,
		&i.ResolutionDueAt,
		&i.FirstRespondedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, tenant_id, title, description, status, priority, category_id, created_by, assigned_to, assigned_team_id, created_at, updated_at, resolved_at, closed_at, first_response_due_at, resolution_due_at, first_responded_at FROM tickets
WHERE tenant_id = ? AND id = ?
LIMIT 1
`

type GetTicketByIDParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetTicketByID(ctx context.Context, arg GetTicketByIDParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByID, arg.TenantID, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CategoryID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.AssignedTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.FirstResponseDueAt,
		&i.ResolutionDueAt,
		&i.FirstRespondedAt,
	)
	return i, err
}

const listTicketsByCreator = `-- name: ListTicketsByCreator :many
SELECT id, tenant_id, title, description, status, priority, category_id, created_by, assigned_to, assigned_team_id, created_at, updated_at, resolved_at, closed_at, first_response_due_at, resolution_due_at, first_responded_at FROM tickets
WHERE tenant_id = ?1 AND created_by = ?2
  AND (?3 IS NULL OR status = ?3)
  AND (?4 IS NULL OR priority = ?4)
  AND (?5 IS NULL OR assigned_to = ?5)
  AND (?6 IS NULL OR assigned_team_id = ?6)
  AND (?7 IS NULL
       OR title LIKE '%' || ?7 || '%'
       OR description LIKE '%' || ?7 || '%')
  AND (?8 IS NULL OR (
        resolved_at IS NULL AND closed_at IS NULL AND (
            (resolution_due_at IS NOT NULL
             AND resolution_due_at < ?8)
         OR (first_response_due_at IS NOT NULL AND first_responded_at IS NULL
             AND first_response_due_at < ?8))))
ORDER BY created_at DESC, id DESC
LIMIT ?10 OFFSET ?9
`

type ListTicketsByCreatorParams struct {
	TenantID       int64       `json:"tenant_id"`
	CreatedBy      int64       `json:"created_by"`
	Status         interface{} `json:"status"`
	Priority       interface{} `json:"priority"`
	AssignedTo     interface{} `json:"assigned_to"`
	TeamID         interface{} `json:"team_id"`
	Search         interface{} `json:"search"`
	BreachedBefore interface{} `json:"breached_before"`
	Offset         int64       `json:"offset"`
	Limit          int64       `json:"limit"`
}

func (q *Queries) ListTicketsByCreator(ctx context.Context, arg ListTicketsByCreatorParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByCreator,
		arg.TenantID,
		arg.CreatedBy,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
		arg.TeamID,
		arg.Search,
		arg.BreachedBefore,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CategoryID,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.AssignedTeamID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.FirstResponseDueAt,
			&i.ResolutionDueAt,
			&i.FirstRespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByTenant = `-- name: ListTicketsByTenant :many
SELECT id, tenant_id, title, description, status, priority, category_id, created_by, assigned_to, assigned_team_id, created_at, updated_at, resolved_at, closed_at, first_response_due_at, resolution_due_at, first_responded_at FROM tickets
WHERE tenant_id = ?1
  AND (?2 IS NULL OR status = ?2)
  AND (?3 IS NULL OR priority = ?3)
  AND (?4 IS NULL OR assigned_to = ?4)
  AND (?5 IS NULL OR assigned_team_id = ?5)
  AND (?6 IS NULL
       OR title LIKE '%' || ?6 || '%'
       OR description LIKE '%' || ?6 || '%')
  AND (?7 IS NULL OR (
        resolved_at IS NULL AND closed_at IS NULL AND (
            (resolution_due_at IS NOT NULL
             AND resolution_due_at < ?7)
         OR (first_response_due_at IS NOT NULL AND first_responded_at IS NULL
             AND first_response_due_at < ?7))))
ORDER BY created_at DESC, id DESC
LIMIT ?9 OFFSET ?8
`

type ListTicketsByTenantParams struct {
	TenantID       int64       `json:"tenant_id"`
	Status         interface{} `json:"status"`
	Priority       interface{} `json:"priority"`
	AssignedTo     interface{} `json:"assigned_to"`
	TeamID         interface{} `json:"team_id"`
	Search         interface{} `json:"search"`
	BreachedBefore interface{} `json:"breached_before"`
	Offset         int64       `json:"offset"`
	Limit          int64       `json:"limit"`
}

func (q *Queries) ListTicketsByTenant(ctx context.Context, arg ListTicketsByTenantParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByTenant,
		arg.TenantID,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
		arg.TeamID,
		arg.Search,
		arg.BreachedBefore,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CategoryID,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.AssignedTeamID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.FirstResponseDueAt,
			&i.ResolutionDueAt,
			&i.FirstRespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampFirstResponse = `-- name: StampFirstResponse :exec
UPDATE tickets
SET first_responded_at = ?
WHERE tenant_id = ? AND id = ? AND first_responded_at IS NULL
`

type StampFirstResponseParams struct {
	FirstRespondedAt sql.NullTime `json:"first_responded_at"`
	TenantID         int64        `json:"tenant_id"`
	ID               int64        `json:"id"`
}

func (q *Queries) StampFirstResponse(ctx context.Context, arg StampFirstResponseParams) error {
	_, err := q.db.ExecContext(ctx, stampFirstResponse, arg.FirstRespondedAt, arg.TenantID, arg.ID)
	return err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET title                 = ?,
    description           = ?,
    status                = ?,
    priority              = ?,
    category_id           = ?,
    assigned_to           = ?,
    assigned_team_id      = ?,
    resolved_at           = ?,
    closed_at             = ?,
    first_response_due_at = ?,
    resolution_due_at     = ?,
    first_responded_at    = ?,
    updated_at            = CURRENT_TIMESTAMP
WHERE tenant_id = ? AND id = ?
RETURNING id, tenant_id, title, description, status, priority, category_id, created_by, assigned_to, assigned_team_id, created_at, updated_at, resolved_at, closed_at, first_response_due_at, resolution_due_at, first_responded_at
`

type UpdateTicketParams struct {
	Title              string        `json:"title"`
	Description        string        `json:"description"`
	Status             string        `json:"status"`
	Priority           string        `json:"priority"`
	CategoryID         int64         `json:"category_id"`
	AssignedTo         sql.NullInt64 `json:"assigned_to"`
	AssignedTeamID     sql.NullInt64 `json:"assigned_team_id"`
	ResolvedAt         sql.NullTime  `json:"resolved_at"`
	ClosedAt           sql.NullTime  `json:"closed_at"`
	FirstResponseDueAt sql.NullTime  `json:"first_response_due_at"`
	ResolutionDueAt    sql.NullTime  `json:"resolution_due_at"`
	FirstRespondedAt   sql.NullTime  `json:"first_responded_at"`
	TenantID           int64         `json:"tenant_id"`
	ID                 int64         `json:"id"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.CategoryID,
		arg.AssignedTo,
		arg.AssignedTeamID,
		arg.ResolvedAt,
		arg.ClosedAt,
		arg.FirstResponseDueAt,
		arg.ResolutionDueAt,
		arg.FirstRespondedAt,
		arg.TenantID,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CategoryID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.AssignedTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.FirstResponseDueAt,
		&i.ResolutionDueAt,
		&i.FirstRespondedAt,
	)
	return i, err
}
