// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_events.sql

package db

import (
	"context"
	"database/sql"
)

const createTicketEvent = `-- name: CreateTicketEvent :one
INSERT INTO ticket_events (tenant_id, ticket_id, actor_id, kind, old_value, new_value)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, tenant_id, ticket_id, actor_id, kind, old_value, new_value, created_at
`

type CreateTicketEventParams struct {
	TenantID int64          `json:"tenant_id"`
	TicketID int64          `json:"ticket_id"`
	ActorID  int64          `json:"actor_id"`
	Kind     string         `json:"kind"`
	OldValue sql.NullString `json:"old_value"`
	NewValue sql.NullString `json:"new_value"`
}

func (q *Queries) CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (TicketEvent, error) {
	row := q.db.QueryRowContext(ctx, createTicketEvent,
		arg.TenantID,
		arg.TicketID,
		arg.ActorID,
		arg.Kind,
		arg.OldValue,
		arg.NewValue,
	)
	var i TicketEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TicketID,
		&i.ActorID,
		&i.Kind,
		&i.OldValue,
		&i.NewValue,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketEvents = `-- name: ListTicketEvents :many
SELECT id, tenant_id, ticket_id, actor_id, kind, old_value, new_value, created_at FROM ticket_events
WHERE tenant_id = ? AND ticket_id = ?
ORDER BY created_at, id
`

type ListTicketEventsParams struct {
	TenantID int64 `json:"tenant_id"`
	TicketID int64 `json:"ticket_id"`
}

func (q *Queries) ListTicketEvents(ctx context.Context, arg ListTicketEventsParams) ([]TicketEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTicketEvents, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketEvent{}
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TicketID,
			&i.ActorID,
			&i.Kind,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
